# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 89e8dfbf40086c3d8431c3bcceeb3d38ae7c79de942843b8f7b65804c6c5da9a7d0419bfb6832b83ec019480d0352e9484952a11c365823d438b8b55cdf6499e

test:
  secret_key_base: a9387c74e61806b285200e5f569ffee27b2194d638787e070e06a025212445f89cdafb542b6a1041ee2c6843450031904ed5d1cf15dc9459d6b91422354b6d59

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
